config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :recipes

  namespace :api do
    namespace :v1 do
      get 'recipes/index'
      get 'recipes/:id', to: 'recipes#show'
      post 'recipes/create'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  UNIT_MAPPING = {
    dash: { name: 'tsp', conv: 1 },
    sprinkle: { name: 'tsp', conv: 0.5 },
    bunch: { name: 'cup', conv: 1 },
    pinch: { name: 'tsp', conv: 0.5 },
    drizzle: { name: 'tbsp', conv: 1 },
    some: { name: 'cup', conv: 0.5 },
    cup: { name: 'cup', conv: 1},
  }

  def as_json(mom: true)
    if mom
      { id: id, 
        quantity: quantity, 
        unit: quantity > 1 ? unit.pluralize : unit, 
        name: name,
      }
    else
      { id: id, 
        quantity: normal_quantity, 
        unit: quantity > 1 ? normal_unit.pluralize : normal_unit, 
        name: name,
      }
    end
  end

  def normal_quantity
    quantity * UNIT_MAPPING[unit.to_sym][:conv]
  end

  def normal_unit
    UNIT_MAPPING[unit.to_sym][:name]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, dependent: :destroy

    def as_json(options = {})
      super(options).merge(
        {
          mom_ingredients: ingredients.as_json(mom: true),
          normal_ingredients: ingredients.as_json(mom: false),
        }
      )
    end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < ApplicationController
    before_action :set_recipe, only: %i[ show edit update destroy ]

    # GET /recipes or /recipes.json
    def index
      @recipes = Recipe.all
      render json: @recipes
    end
  
    # GET /recipes/1 or /recipes/1.json
    def show
      render json: @recipe.to_json(include: :ingredients)
    end
  
    # GET /recipes/new
    def new
      @recipe = Recipe.new
    end
  
    # GET /recipes/1/edit
    def edit
    end
  
    # POST /recipes or /recipes.json
    def create
      @recipe = Recipe.new(recipe_params)
  
      respond_to do |format|
        if @recipe.save
          format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
          format.json { render :show, status: :created, location: @recipe }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /recipes/1 or /recipes/1.json
    def update
      respond_to do |format|
        if @recipe.update(recipe_params)
          format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
          format.json { render :show, status: :ok, location: @recipe }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /recipes/1 or /recipes/1.json
    def destroy
      @recipe.destroy
  
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_recipe
        @recipe = Recipe.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def recipe_params
        params.require(:recipe).permit(:title, :description)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  # GET /recipes or /recipes.json
  def index
  end
end

app/helpers/api/v1/recipes_helper.rb
module Api::V1::RecipesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MomsRecipeBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Title:</strong>
    <%= recipe.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>